import { createHmac, randomUUID, timingSafeEqual } from 'node:crypto';

/**
 * Self-contained HS256 JWT signer + verifier for Univercart Connect
 * magic links. We avoid the `jsonwebtoken` dependency to keep the
 * package lean and to make the algorithm explicit (one line of crypto,
 * zero "alg: none" misconfiguration surface).
 *
 * The payload schema is fixed at the issuer side (us). Partners just
 * `JSON.parse` after verifying the signature and trust the field
 * shape because they pinned `iss=univercart` and `aud=<partnerSlug>`.
 */

export interface MagicLinkClaims {
  sub: string; // subscriptionId (also used as externalUserId in webhook payloads)
  email: string;
  name: string;
  role: string; // partnerRoleSlug
  iss: 'univercart';
  aud: string; // partner slug
  exp: number; // unix seconds
  iat: number; // unix seconds
  jti: string; // tracked in entitlement_tokens for single-use
}

function b64urlEncode(input: Buffer | string): string {
  return Buffer.from(input)
    .toString('base64')
    .replace(/=+$/u, '')
    .replace(/\+/g, '-')
    .replace(/\//g, '_');
}

function b64urlDecode(input: string): Buffer {
  const padded = input.replace(/-/g, '+').replace(/_/g, '/');
  const pad = padded.length % 4 === 0 ? '' : '='.repeat(4 - (padded.length % 4));
  return Buffer.from(padded + pad, 'base64');
}

function hmacSha256(secret: string, data: string): string {
  return b64urlEncode(createHmac('sha256', secret).update(data).digest());
}

export interface SignMagicLinkInput {
  subscriptionId: string;
  email: string;
  name: string;
  partnerSlug: string;
  partnerRoleSlug: string;
  jwtSigningSecret: string;
  expiresInSeconds?: number; // default 72h
  jti?: string; // pre-generated by caller so they can persist before issuing
}

export interface SignMagicLinkResult {
  jwt: string;
  jti: string;
  expiresAt: Date;
}

/**
 * Issue a JWT magic link for a subscription. Returns the signed token
 * + `jti` (which must be persisted in `entitlement_tokens` BEFORE the
 * token is handed to the buyer — otherwise the redeem endpoint will
 * 404 it).
 */
export function signMagicLink(input: SignMagicLinkInput): SignMagicLinkResult {
  const expiresInSec = input.expiresInSeconds ?? 72 * 60 * 60;
  const now = Math.floor(Date.now() / 1000);
  const exp = now + expiresInSec;
  const jti = input.jti ?? randomUUID();
  const claims: MagicLinkClaims = {
    sub: input.subscriptionId,
    email: input.email,
    name: input.name,
    role: input.partnerRoleSlug,
    iss: 'univercart',
    aud: input.partnerSlug,
    exp,
    iat: now,
    jti,
  };
  const headerSegment = b64urlEncode(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const payloadSegment = b64urlEncode(JSON.stringify(claims));
  const signingInput = `${headerSegment}.${payloadSegment}`;
  const signature = hmacSha256(input.jwtSigningSecret, signingInput);
  return {
    jwt: `${signingInput}.${signature}`,
    jti,
    expiresAt: new Date(exp * 1000),
  };
}

export interface VerifyMagicLinkOptions {
  jwtSigningSecret: string;
  audience: string; // partner slug
  /** Override `now` for tests. Unix seconds. */
  clockNowSec?: number;
}

export type VerifyMagicLinkResult =
  | { ok: true; claims: MagicLinkClaims }
  | {
      ok: false;
      reason: 'malformed' | 'bad_signature' | 'expired' | 'bad_audience' | 'bad_issuer';
    };

/**
 * Verify a magic-link JWT. Does NOT check `jti` against the database;
 * the caller is responsible for calling the redeem endpoint after a
 * successful verify (single-use enforcement is server-side, not
 * crypto-side).
 */
export function verifyMagicLink(jwt: string, opts: VerifyMagicLinkOptions): VerifyMagicLinkResult {
  const parts = jwt.split('.');
  if (parts.length !== 3) return { ok: false, reason: 'malformed' };
  const headerSegment = parts[0];
  const payloadSegment = parts[1];
  const providedSig = parts[2];
  if (!headerSegment || !payloadSegment || !providedSig) {
    return { ok: false, reason: 'malformed' };
  }

  let header: { alg?: string; typ?: string };
  let claims: MagicLinkClaims;
  try {
    header = JSON.parse(b64urlDecode(headerSegment).toString('utf-8'));
    claims = JSON.parse(b64urlDecode(payloadSegment).toString('utf-8')) as MagicLinkClaims;
  } catch {
    return { ok: false, reason: 'malformed' };
  }
  if (header.alg !== 'HS256' || header.typ !== 'JWT') return { ok: false, reason: 'malformed' };

  const expectedSig = hmacSha256(opts.jwtSigningSecret, `${headerSegment}.${payloadSegment}`);
  const a = Buffer.from(providedSig);
  const b = Buffer.from(expectedSig);
  if (a.length !== b.length || !timingSafeEqual(a, b))
    return { ok: false, reason: 'bad_signature' };

  const nowSec = opts.clockNowSec ?? Math.floor(Date.now() / 1000);
  if (typeof claims.exp !== 'number' || claims.exp < nowSec)
    return { ok: false, reason: 'expired' };
  if (claims.iss !== 'univercart') return { ok: false, reason: 'bad_issuer' };
  if (claims.aud !== opts.audience) return { ok: false, reason: 'bad_audience' };

  return { ok: true, claims };
}
